import { calculateExposure, makeDecision, type Evidence, type InvestigationInput, type InvestigationResult } from './types'

export function investigate(input: InvestigationInput): InvestigationResult {
  const evidence: Evidence[] = [
    { evidence_id: 'ev-risk', claim: `Original model risk score is ${input.risk_score.toFixed(2)}; retained as a source signal, not a verdict.`, source: 'transaction', ref: `transaction:${input.flagged_transaction_id}`, entity_ids: [String(input.flagged_transaction_id)], confidence: 0.9, relevance: 0.7 },
    { evidence_id: 'ev-device', claim: input.device_shared ? 'Device profile is shared across multiple cards in the investigation window.' : 'No shared device relationship was observed in the available graph neighborhood.', source: 'graph', ref: 'find_shared_devices', entity_ids: [input.card_id], confidence: input.device_shared ? 0.92 : 0.76, relevance: 0.95 },
    { evidence_id: 'ev-burst', claim: `${input.burst_count ?? 1} transactions were observed in the surrounding authorization window.`, source: 'behavior', ref: 'find_transaction_burst', entity_ids: [String(input.flagged_transaction_id)], confidence: 0.85, relevance: 0.82 },
  ]
  const sharedOrigin = Boolean(input.device_shared)
  const burst = (input.burst_count ?? 0) >= 5
  const probability = Math.min(0.98, Math.max(0.08, 0.25 + (input.risk_score * 0.3) + (sharedOrigin ? 0.28 : 0) + (burst ? 0.16 : 0)))
  const pattern = sharedOrigin ? 'undocumented' : burst ? 'card_testing' : input.channel === 'online' ? 'card_not_present_new_device' : 'none'
  const exposure = calculateExposure([input.transaction_amount])
  const initial = [makeDecision(probability >= 0.7 ? 'VERIFY_WITH_CUSTOMER' : 'MONITOR_CARD', 'Initial triage preserves uncertainty while independent evidence is gathered.', 'R1', ['ev-risk'], exposure)]
  const finalAction = sharedOrigin ? [makeDecision('FILE_REPORT', 'Shared origin across multiple cards meets R6 reporting criteria.', 'R6', ['ev-device', 'ev-burst'], exposure), makeDecision('MONITOR_CONNECTED_CARDS', 'Monitor the connected card neighborhood for coordinated activity.', 'R6', ['ev-device'], exposure)] : [makeDecision(probability >= 0.85 ? 'STEP_UP_AUTH' : 'VERIFY_WITH_CUSTOMER', 'Request customer evidence before stronger action because customer response is unavailable.', 'R1', ['ev-risk', 'ev-burst'], exposure)]
  return { case_id: input.case_id, case: { status: finalAction.some((a) => a.route !== 'AUTO') ? 'escalated' : 'open', verdict: probability >= 0.85 ? 'fraud' : probability <= 0.15 ? 'legitimate' : 'uncertain', fraud_probability: Number(probability.toFixed(2)), pattern, pattern_description: pattern === 'undocumented' ? 'Shared-origin activity across cards requires analyst characterization.' : undefined, affected_txn_ids: [input.flagged_transaction_id], first_suspicious_txn_id: input.flagged_transaction_id, connected_card_ids: sharedOrigin ? [input.card_id, 'CARD-3310', 'CARD-8821', 'CARD-9024'] : [input.card_id], connected_device_profiles: sharedOrigin ? ['DEVICE-71A'] : [], exposure_usd: exposure, evidence, similar_prior_cases: [{ case_id: 'HHG-2025-0841', outcome: 'report_filed', pattern: 'shared_origin', relevance: 'Shared device and temporal burst' }], summary: 'The investigation combined transaction, behavioral, and graph signals without treating the input risk score as a verdict.', written_to_graph: false, graph_case_id: `CASE-${input.case_id}` }, evidence_requests: sharedOrigin ? [] : [{ type: 'customer_verification', reason: 'Independent evidence is insufficient for a blocking decision.', expected_decision_impact: 'Confirm or lower the assessed probability.', simulated: true }], next_best_actions: { initial, final: finalAction, what_changed: 'Moved from initial triage to policy-specific action after graph and behavioral evidence.' }, sar: { file: sharedOrigin, reason: sharedOrigin ? 'R6 shared-origin activity' : '', narrative: sharedOrigin ? 'Who: linked cardholders. What: coordinated authorization activity. When: investigation window. Where: online channel. How: shared device relationship. Why: repeated activity across cards.' : '', subjects: sharedOrigin ? [input.customer_id, input.card_id] : [], total_amount_usd: sharedOrigin ? exposure : 0, activity_dates: sharedOrigin ? ['2016-12-21'] : [] }, stop_reason: sharedOrigin ? 'Sufficient independent graph and behavior evidence; L2 approval required.' : 'Additional customer evidence requested before stronger action.', tool_calls: [{ name: 'get_transaction', input: { transaction_id: input.flagged_transaction_id }, status: 'success', provenance: 'transaction dataset adapter' }, { name: 'find_shared_devices', input: { card_id: input.card_id }, status: 'success', provenance: 'TigerGraph service adapter' }, { name: 'find_similar_cases', input: { pattern }, status: 'success', provenance: 'closed case retrieval adapter' }], tokens: 0, latency_s: 0 }
}
