'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowUpRight, CheckCircle2, ChevronDown, CircleDot, Clock3, FileText, GitBranch, Menu, Play, Search, ShieldAlert, ShieldCheck, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'
import { cn } from '@/lib/utils'
import type { InvestigationResult } from '@/lib/fraud/types'
import { benchmarkCases, type BenchmarkCase } from '@/lib/fraud/case-data'

type CaseRow = BenchmarkCase & { id: string; subject: string; signal: string; status: 'Investigating' | 'Approval required' | 'Closed'; time: string }
const cases: CaseRow[] = benchmarkCases.map((item) => ({
  ...item,
  id: item.case_id,
  subject: `${item.customer_id} · ${item.card_id}`,
  signal: item.trigger_text ?? `${item.trigger_type.replace('_', ' ')} trigger`,
  status: item.trigger_type === 'analyst_request' ? 'Approval required' : item.trigger_type === 'customer_report' ? 'Investigating' : 'Closed',
  time: item.opened_at,
}))

function displayScore(item: BenchmarkCase) { return item.risk_score ?? 0 }
function StatusForCase({ status }: { status: CaseRow['status'] }) { return status }
const caseDataValidation = `Loaded ${benchmarkCases.length} official benchmark cases`

function ScoreRing({ score }: { score: number }) { return <div className="score-ring" style={{ '--score': `${score * 100}%` } as React.CSSProperties}><span>{Math.round(score * 100)}</span></div> }
function StatusBadge({ status }: { status: CaseRow['status'] }) { return <Badge variant="outline" className={cn('status-badge', status === 'Approval required' && 'status-amber', status === 'Investigating' && 'status-blue', status === 'Closed' && 'status-green')}><span className="status-dot" />{status}</Badge> }
function Metric({ label, value, delta, icon, tone }: { label: string; value: string; delta: string; icon: React.ReactNode; tone: string }) { return <Card className="metric-card"><CardContent><div className={cn('metric-icon', `metric-${tone}`)}>{icon}</div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small>{delta}</small></div></CardContent></Card> }
function Entity({ label, value }: { label: string; value: string }) { return <div className="entity"><span>{label}</span><strong>{value}</strong></div> }

export default function Page() {
  const [selected, setSelected] = useState('HHG-017'); const [mobileNav, setMobileNav] = useState(false); const [mainTab, setMainTab] = useState('Overview'); const [detailTab, setDetailTab] = useState('Overview'); const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const [result, setResult] = useState<InvestigationResult | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [benchmark, setBenchmark] = useState<string | null>(null)
  const activeCase = useMemo(() => cases.find((item) => item.id === selected) ?? cases[0], [selected])
  const visibleCases = cases.filter((item) => !query || `${item.case_id} ${item.customer_id} ${item.card_id} ${item.flagged_txn_id} ${item.trigger_type} ${item.trigger_text ?? ''}`.toLowerCase().includes(query.toLowerCase())).filter((item) => filter === 'All' || (filter === 'Needs review' ? item.status !== 'Closed' : (item.risk_score ?? 0) >= 0.7))
  async function investigateCase() { if (!activeCase) return; setBusy(true); setMessage(`Investigating ${activeCase.case_id}…`); setResult(null); try { const response = await fetch('/api/investigate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ case_id: activeCase.case_id, customer_id: activeCase.customer_id, card_id: activeCase.card_id, flagged_txn_id: activeCase.flagged_txn_id, trigger_type: activeCase.trigger_type, trigger_text: activeCase.trigger_text, risk_score: activeCase.risk_score ?? null }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Unknown API error'); setResult(data); setMessage('Investigation complete.'); } catch (error) { setMessage(`Investigation failed: ${error instanceof Error ? error.message : 'Unknown error'}`) } finally { setBusy(false) } }
  async function runBenchmark() { setBenchmark(`Validating ${benchmarkCases.length} official benchmark cases…`); try { const response = await Promise.all(cases.map(async (item) => { const res = await fetch('/api/investigate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ case_id: item.case_id, customer_id: item.customer_id, card_id: item.card_id, flagged_txn_id: item.flagged_txn_id, trigger_type: item.trigger_type, trigger_text: item.trigger_text, risk_score: item.risk_score ?? null }) }); return `${item.case_id}: ${res.ok ? 'validated' : 'error'}` })); setBenchmark(`${response.length} official benchmark cases recognized.`) } catch (error) { setBenchmark(`Benchmark validation failed: ${error instanceof Error ? error.message : 'Unknown error'}`) } }
  const displayed = result?.case
  return <div className="app-shell">
    <aside className={cn('sidebar', mobileNav && 'sidebar-open')}><div className="brand"><div className="brand-mark"><ShieldAlert /></div><div><strong>ARGUS</strong><span>Fraud Intelligence</span></div><button className="sidebar-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X /></button></div><div className="workspace-label">WORKSPACE</div><nav className="nav-stack" aria-label="Primary navigation">{['Overview', 'Investigations', 'Case memory', 'Benchmarks'].map((item, index) => <button key={item} className={cn('nav-item', mainTab === item && 'nav-item-active')} onClick={() => { setMainTab(item); setMobileNav(false); if (item === 'Benchmarks') setBenchmark('Benchmark runner ready. Run it from the top bar.') }}>{index === 0 ? <CircleDot /> : index === 1 ? <ShieldAlert /> : index === 2 ? <GitBranch /> : <FileText />}<span>{item}</span>{item === 'Investigations' && <span className="nav-count">4</span>}</button>)}</nav><div className="sidebar-spacer" /><div className="system-card"><div className="system-header"><span className="live-dot" />Runtime status</div><p>TigerGraph: unconfigured<br />Agent runtime: ready</p><div className="system-meta"><span>Mode</span><strong>Deterministic</strong></div></div><div className="profile"><div className="avatar">AR</div><div><strong>Analyst workspace</strong><span>Tier 2 reviewer</span></div><ChevronDown /></div></aside>
    {mobileNav && <button className="mobile-scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}
    <main className="main-content"><header className="topbar"><div className="topbar-left"><button className="menu-button" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div><div className="eyebrow">OPERATIONS / {mainTab.toUpperCase()}</div><h1>{mainTab === 'Overview' ? 'Investigation command center' : mainTab}</h1></div></div><div className="topbar-actions"><div className="search-box"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases, entities, transactions" aria-label="Search" /></div><Button variant="outline" size="sm" onClick={runBenchmark} disabled={busy}><Play data-icon="inline-start" />{benchmark ? 'Benchmark running…' : 'Run benchmark'}</Button><div className="avatar avatar-small">JD</div></div></header>
      <div className="content-wrap"><section className="metric-grid"><Metric label="Open investigations" value="24" delta="Live workspace" icon={<ShieldAlert />} tone="red" /><Metric label="Pending approvals" value="07" delta="3 high exposure" icon={<Clock3 />} tone="amber" /><Metric label="Cases closed today" value="18" delta="92% within SLA" icon={<CheckCircle2 />} tone="green" /><Metric label="Benchmark pass rate" value="—" delta="Run to calculate" icon={<Sparkles />} tone="violet" /></section>
        {message && <div className={cn('runtime-message', message.startsWith('Investigation failed') && 'runtime-error')} role="status">{message}</div>}{benchmark && <div className="runtime-message" role="status">{benchmark}</div>}
        <section className="workspace-grid"><Card className="case-list-card"><CardHeader className="section-header"><div><CardTitle>Active investigations</CardTitle><CardDescription>Signals ranked by decision urgency</CardDescription></div><Button variant="ghost" size="icon" aria-label="Filter cases" onClick={() => setFilter(filter === 'All' ? 'Needs review' : filter === 'Needs review' ? 'High exposure' : 'All')}><SlidersHorizontal /></Button></CardHeader><CardContent className="case-list-content"><div className="case-filters">{['All', 'Needs review', 'High exposure'].map((item) => <button key={item} className={filter === item ? 'filter-active' : ''} onClick={() => setFilter(item)}>{item}{item === 'All' && <span>{visibleCases.length}</span>}</button>)}</div>{visibleCases.map((item) => <button key={item.id} className={cn('case-row', item.id === selected && 'case-row-selected')} onClick={() => { setSelected(item.id); setResult(null); setMessage(`Selected ${item.id}. Ready to investigate.`) }}><div className="case-row-top"><span className="case-id">{item.id}</span><StatusBadge status={item.status} /></div><strong>{item.subject}</strong><div className="case-row-bottom"><span>{item.signal}</span><span>TXN-{item.flagged_txn_id}</span></div><div className="case-row-footer"><span>{item.opened_at}</span><span className="mini-score"><i style={{ width: `${displayScore(item) * 100}%` }} />{item.risk_score == null ? 'Not supplied' : `${Math.round(item.risk_score * 100)}% risk`}</span></div></button>)}</CardContent></Card>
          <div className="detail-column"><Card className="detail-card"><CardHeader className="detail-header"><div><div className="case-heading"><span className="case-id">{activeCase.id}</span><StatusBadge status={activeCase.status} /></div><CardTitle>{activeCase.signal}</CardTitle><CardDescription>{activeCase.trigger_text ?? `Triggered by ${activeCase.trigger_type}`} · {activeCase.opened_at}</CardDescription></div><Button variant="outline" size="sm" onClick={investigateCase} disabled={busy}>{busy ? 'Investigating…' : 'Investigate'} <ArrowUpRight data-icon="inline-end" /></Button></CardHeader><CardContent><div className="entity-strip"><Entity label="Customer" value={activeCase.customer_id} /><Entity label="Card" value={activeCase.card_id} /><Entity label="Flagged transaction" value={`TXN-${activeCase.flagged_txn_id}`} /><Entity label="Risk score" value={activeCase.risk_score == null ? 'Not supplied' : activeCase.risk_score.toFixed(2)} /></div><div className="assessment"><div><div className="eyebrow">AGENT ASSESSMENT</div><h3>{displayed ? `${displayed.verdict} · ${displayed.pattern}` : 'Investigation not yet run'}</h3><p>{displayed?.summary ?? 'Select a case and run the investigation to retrieve graph, behavioral, historical, and policy evidence.'}</p><div className="assessment-tags">{displayed ? <><Badge className="tag-red">{Math.round(displayed.fraud_probability * 100)}% assessed</Badge><Badge className="tag-amber">{displayed.status}</Badge></> : <Badge variant="outline">Awaiting investigation</Badge>}</div></div><ScoreRing score={displayed?.fraud_probability ?? displayScore(activeCase)} /></div><Separator /><div className="detail-tabs">{['Overview', 'Evidence', 'Graph', 'Timeline'].map((item) => <button key={item} className={cn(detailTab === item && 'detail-tab-active')} onClick={() => setDetailTab(item)}>{item}</button>)}</div>{displayed ? <div className="evidence-list">{displayed.evidence.map((item) => <div className="evidence-item" key={item.evidence_id}><div className={cn('evidence-icon', item.source === 'graph' ? 'evidence-red' : item.source === 'behavior' ? 'evidence-amber' : 'evidence-blue')}>{item.source === 'graph' ? <GitBranch /> : item.source === 'behavior' ? <AlertTriangle /> : <ShieldCheck />}</div><div><div className="evidence-type">{item.source.toUpperCase()}</div><strong>{item.claim}</strong><span>{item.ref}</span></div><CheckCircle2 className="evidence-check" /></div>)}</div> : <div className="empty-evidence">Run the investigation to populate evidence with provenance.</div>}</CardContent></Card>
            <div className="bottom-grid"><Card><CardHeader><CardTitle>Next-best action</CardTitle><CardDescription>Policy-aware recommendation</CardDescription></CardHeader><CardContent>{displayed ? <><div className="action-main"><div className="action-icon"><ShieldAlert /></div><div><div className="eyebrow">INITIAL → FINAL</div><h3>{result.next_best_actions.final.map((item) => item.action).join(' · ')}</h3><p>{result.next_best_actions.final.map((item) => item.reason).join(' ')}</p></div></div><div className="action-meta"><span><b>Route</b><Badge variant="outline" className="status-amber">{result.next_best_actions.final.map((item) => item.route).join(' / ')}</Badge></span><span><b>Exposure</b><strong>${result.case.exposure_usd.toLocaleString()}</strong></span></div><Button className="full-button" onClick={() => setMessage('Action review opened. Approval-required actions are not executed automatically.')}>Review approval request <ArrowUpRight data-icon="inline-end" /></Button></> : <div className="empty-evidence">No action recommendation until evidence is assessed.</div>}</CardContent></Card><Card><CardHeader><CardTitle>Investigation timeline</CardTitle><CardDescription>Auditable agent activity</CardDescription></CardHeader><CardContent><Timeline result={result} /></CardContent></Card></div></div>
        </section><div className="footer-note"><span><span className="live-dot" />{result?.system_status?.message ?? 'Live investigation workspace'}</span><span>{result ? `${result.tool_calls.length} tool calls recorded` : 'No investigation run'}</span><span>Build 0.8.4 · deterministic mode</span></div></div></main></div>
}
function Timeline({ result }: { result: InvestigationResult | null }) { return <div className="timeline">{(result ? result.tool_calls : [{ name: 'Ready for investigation', provenance: 'Select a case and run Investigate', status: 'success' }]).map((item, index) => <div key={`${item.name}-${index}`}><span className={cn('timeline-dot', item.status === 'success' ? 'done' : 'active')} /><div><strong>{item.name}</strong><span>{item.provenance}</span><small>{result ? item.status : 'idle'}</small></div></div>)}</div> }
