'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowUpRight, CheckCircle2, ChevronDown, CircleDot, Clock3, FileText, GitBranch, Menu, Play, Search, ShieldAlert, ShieldCheck, SlidersHorizontal, Sparkles, X } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'
import { cn } from '@/lib/utils'
import type { InvestigationResult } from '@/lib/fraud/types'

type CaseRow = { id: string; customer_id: string; card_id: string; subject: string; signal: string; amount: number; transaction_id: number; score: number; channel: 'online' | 'in_person'; device_shared: boolean; burst_count: number; status: 'Investigating' | 'Approval required' | 'Closed'; time: string }
const cases: CaseRow[] = [
  { id: 'HHG-017', customer_id: 'CUST-008421', card_id: 'CARD-1042', subject: 'CUST-008421 · CARD-1042', signal: 'Shared device cluster', amount: 1842.6, transaction_id: 3005419, score: .91, channel: 'online', device_shared: true, burst_count: 6, status: 'Approval required', time: '2 min ago' },
  { id: 'HHG-004', customer_id: 'CUST-002118', card_id: 'CARD-0918', subject: 'CUST-002118 · CARD-0918', signal: 'Card testing burst', amount: 186.4, transaction_id: 3005425, score: .87, channel: 'online', device_shared: false, burst_count: 7, status: 'Investigating', time: '18 min ago' },
  { id: 'HHG-012', customer_id: 'CUST-004507', card_id: 'CARD-2201', subject: 'CUST-004507 · CARD-2201', signal: 'New device / CNP', amount: 428, transaction_id: 3011012, score: .74, channel: 'online', device_shared: false, burst_count: 2, status: 'Investigating', time: '41 min ago' },
  { id: 'HHG-009', customer_id: 'CUST-001992', card_id: 'CARD-0674', subject: 'CUST-001992 · CARD-0674', signal: 'Out-of-region activity', amount: 96.18, transaction_id: 3009876, score: .38, channel: 'in_person', device_shared: false, burst_count: 1, status: 'Closed', time: '1 hr ago' },
]

function ScoreRing({ score }: { score: number }) { return <div className="score-ring" style={{ '--score': `${score * 100}%` } as React.CSSProperties}><span>{Math.round(score * 100)}</span></div> }
function StatusBadge({ status }: { status: CaseRow['status'] }) { return <Badge variant="outline" className={cn('status-badge', status === 'Approval required' && 'status-amber', status === 'Investigating' && 'status-blue', status === 'Closed' && 'status-green')}><span className="status-dot" />{status}</Badge> }
function Metric({ label, value, delta, icon, tone }: { label: string; value: string; delta: string; icon: React.ReactNode; tone: string }) { return <Card className="metric-card"><CardContent><div className={cn('metric-icon', `metric-${tone}`)}>{icon}</div><div className="metric-copy"><span>{label}</span><strong>{value}</strong><small>{delta}</small></div></CardContent></Card> }
function Entity({ label, value }: { label: string; value: string }) { return <div className="entity"><span>{label}</span><strong>{value}</strong></div> }

export default function Page() {
  const [selected, setSelected] = useState('HHG-017'); const [mobileNav, setMobileNav] = useState(false); const [tab, setTab] = useState('Overview'); const [filter, setFilter] = useState('All'); const [query, setQuery] = useState(''); const [result, setResult] = useState<InvestigationResult | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [benchmark, setBenchmark] = useState<string | null>(null)
  const activeCase = useMemo(() => cases.find((item) => item.id === selected) ?? cases[0], [selected])
  const visibleCases = cases.filter((item) => !query || `${item.id} ${item.subject} ${item.signal}`.toLowerCase().includes(query.toLowerCase())).filter((item) => filter === 'All' || (filter === 'Needs review' ? item.status !== 'Closed' : item.amount > 500))
  async function investigateCase() { if (!activeCase) return; setBusy(true); setMessage(`Investigating ${activeCase.id}…`); setResult(null); try { const response = await fetch('/api/investigate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ case_id: activeCase.id, customer_id: activeCase.customer_id, card_id: activeCase.card_id, flagged_transaction_id: activeCase.transaction_id, transaction_amount: activeCase.amount, risk_score: activeCase.score, channel: activeCase.channel, device_shared: activeCase.device_shared, burst_count: activeCase.burst_count }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Unknown API error'); setResult(data); setMessage('Investigation complete.'); } catch (error) { setMessage(`Investigation failed: ${error instanceof Error ? error.message : 'Unknown error'}`) } finally { setBusy(false) } }
  async function runBenchmark() { setBenchmark('Running 20 benchmark cases…'); try { const response = await Promise.all(cases.map(async (item) => { const res = await fetch('/api/investigate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ case_id: item.id, customer_id: item.customer_id, card_id: item.card_id, flagged_transaction_id: item.transaction_id, transaction_amount: item.amount, risk_score: item.score, channel: item.channel, device_shared: item.device_shared, burst_count: item.burst_count }) }); return `${item.id}: ${res.ok ? 'validated' : 'error'}` })); setBenchmark(`${response.length} configured cases executed in the active workspace. Full HHG-001–020 dataset requires project data files.`) } catch (error) { setBenchmark(`Benchmark failed: ${error instanceof Error ? error.message : 'Unknown error'}`) } }
  const displayed = result?.case
  return <div className="app-shell">
    <aside className={cn('sidebar', mobileNav && 'sidebar-open')}><div className="brand"><div className="brand-mark"><ShieldAlert /></div><div><strong>ARGUS</strong><span>Fraud Intelligence</span></div><button className="sidebar-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X /></button></div><div className="workspace-label">WORKSPACE</div><nav className="nav-stack" aria-label="Primary navigation">{['Overview', 'Investigations', 'Case memory', 'Benchmarks'].map((item, index) => <button key={item} className={cn('nav-item', tab === item && 'nav-item-active')} onClick={() => { setTab(item); setMobileNav(false); if (item === 'Benchmarks') setBenchmark('Benchmark runner ready. Run it from the top bar.') }}>{index === 0 ? <CircleDot /> : index === 1 ? <ShieldAlert /> : index === 2 ? <GitBranch /> : <FileText />}<span>{item}</span>{item === 'Investigations' && <span className="nav-count">4</span>}</button>)}</nav><div className="sidebar-spacer" /><div className="system-card"><div className="system-header"><span className="live-dot" />Runtime status</div><p>TigerGraph: unconfigured<br />Agent runtime: ready</p><div className="system-meta"><span>Mode</span><strong>Deterministic</strong></div></div><div className="profile"><div className="avatar">AR</div><div><strong>Analyst workspace</strong><span>Tier 2 reviewer</span></div><ChevronDown /></div></aside>
    {mobileNav && <button className="mobile-scrim" onClick={() => setMobileNav(false)} aria-label="Close navigation" />}
    <main className="main-content"><header className="topbar"><div className="topbar-left"><button className="menu-button" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div><div className="eyebrow">OPERATIONS / {tab.toUpperCase()}</div><h1>{tab === 'Overview' ? 'Investigation command center' : tab}</h1></div></div><div className="topbar-actions"><div className="search-box"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search cases, entities, transactions" aria-label="Search" /></div><Button variant="outline" size="sm" onClick={runBenchmark} disabled={busy}><Play data-icon="inline-start" />{benchmark ? 'Benchmark running…' : 'Run benchmark'}</Button><div className="avatar avatar-small">JD</div></div></header>
      <div className="content-wrap"><section className="metric-grid"><Metric label="Open investigations" value="24" delta="Live workspace" icon={<ShieldAlert />} tone="red" /><Metric label="Pending approvals" value="07" delta="3 high exposure" icon={<Clock3 />} tone="amber" /><Metric label="Cases closed today" value="18" delta="92% within SLA" icon={<CheckCircle2 />} tone="green" /><Metric label="Benchmark pass rate" value="—" delta="Run to calculate" icon={<Sparkles />} tone="violet" /></section>
        {message && <div className={cn('runtime-message', message.startsWith('Investigation failed') && 'runtime-error')} role="status">{message}</div>}{benchmark && <div className="runtime-message" role="status">{benchmark}</div>}
        <section className="workspace-grid"><Card className="case-list-card"><CardHeader className="section-header"><div><CardTitle>Active investigations</CardTitle><CardDescription>Signals ranked by decision urgency</CardDescription></div><Button variant="ghost" size="icon" aria-label="Filter cases" onClick={() => setFilter(filter === 'All' ? 'Needs review' : filter === 'Needs review' ? 'High exposure' : 'All')}><SlidersHorizontal /></Button></CardHeader><CardContent className="case-list-content"><div className="case-filters">{['All', 'Needs review', 'High exposure'].map((item) => <button key={item} className={filter === item ? 'filter-active' : ''} onClick={() => setFilter(item)}>{item}{item === 'All' && <span>{visibleCases.length}</span>}</button>)}</div>{visibleCases.map((item) => <button key={item.id} className={cn('case-row', item.id === selected && 'case-row-selected')} onClick={() => { setSelected(item.id); setResult(null); setMessage(`Selected ${item.id}. Ready to investigate.`) }}><div className="case-row-top"><span className="case-id">{item.id}</span><StatusBadge status={item.status} /></div><strong>{item.subject}</strong><div className="case-row-bottom"><span>{item.signal}</span><span>${item.amount.toLocaleString()}</span></div><div className="case-row-footer"><span>{item.time}</span><span className="mini-score"><i style={{ width: `${item.score * 100}%` }} />{Math.round(item.score * 100)}% assessed</span></div></button>)}</CardContent></Card>
          <div className="detail-column"><Card className="detail-card"><CardHeader className="detail-header"><div><div className="case-heading"><span className="case-id">{activeCase.id}</span><StatusBadge status={activeCase.status} /></div><CardTitle>{activeCase.signal}</CardTitle><CardDescription>Triggered by investigation signal · {activeCase.time}</CardDescription></div><Button variant="outline" size="sm" onClick={investigateCase} disabled={busy}>{busy ? 'Investigating…' : 'Investigate'} <ArrowUpRight data-icon="inline-end" /></Button></CardHeader><CardContent><div className="entity-strip"><Entity label="Customer" value={activeCase.customer_id} /><Entity label="Card" value={activeCase.card_id} /><Entity label="Flagged transaction" value={`TXN-${activeCase.transaction_id}`} /><Entity label="Risk score" value={activeCase.score.toFixed(2)} /></div><div className="assessment"><div><div className="eyebrow">AGENT ASSESSMENT</div><h3>{displayed ? `${displayed.verdict} · ${displayed.pattern}` : 'Investigation not yet run'}</h3><p>{displayed?.summary ?? 'Select a case and run the investigation to retrieve graph, behavioral, historical, and policy evidence.'}</p><div className="assessment-tags">{displayed ? <><Badge className="tag-red">{Math.round(displayed.fraud_probability * 100)}% assessed</Badge><Badge className="tag-amber">{displayed.status}</Badge></> : <Badge variant="outline">Awaiting investigation</Badge>}</div></div><ScoreRing score={displayed?.fraud_probability ?? activeCase.score} /></div><Separator /><div className="detail-tabs">{['Overview', 'Evidence', 'Graph', 'Timeline'].map((item) => <button key={item} className={cn(tab === item && 'detail-tab-active')} onClick={() => setTab(item)}>{item}</button>)}</div>{displayed ? <div className="evidence-list">{displayed.evidence.map((item) => <div className="evidence-item" key={item.evidence_id}><div className={cn('evidence-icon', item.source === 'graph' ? 'evidence-red' : item.source === 'behavior' ? 'evidence-amber' : 'evidence-blue')}>{item.source === 'graph' ? <GitBranch /> : item.source === 'behavior' ? <AlertTriangle /> : <ShieldCheck />}</div><div><div className="evidence-type">{item.source.toUpperCase()}</div><strong>{item.claim}</strong><span>{item.ref}</span></div><CheckCircle2 className="evidence-check" /></div>)}</div> : <div className="empty-evidence">Run the investigation to populate evidence with provenance.</div>}</CardContent></Card>
            <div className="bottom-grid"><Card><CardHeader><CardTitle>Next-best action</CardTitle><CardDescription>Policy-aware recommendation</CardDescription></CardHeader><CardContent>{displayed ? <><div className="action-main"><div className="action-icon"><ShieldAlert /></div><div><div className="eyebrow">INITIAL → FINAL</div><h3>{result.next_best_actions.final.map((item) => item.action).join(' · ')}</h3><p>{result.next_best_actions.final.map((item) => item.reason).join(' ')}</p></div></div><div className="action-meta"><span><b>Route</b><Badge variant="outline" className="status-amber">{result.next_best_actions.final.map((item) => item.route).join(' / ')}</Badge></span><span><b>Exposure</b><strong>${result.case.exposure_usd.toLocaleString()}</strong></span></div><Button className="full-button" onClick={() => setMessage('Action review opened. Approval-required actions are not executed automatically.')}>Review approval request <ArrowUpRight data-icon="inline-end" /></Button></> : <div className="empty-evidence">No action recommendation until evidence is assessed.</div>}</CardContent></Card><Card><CardHeader><CardTitle>Investigation timeline</CardTitle><CardDescription>Auditable agent activity</CardDescription></CardHeader><CardContent><Timeline result={result} /></CardContent></Card></div></div>
        </section><div className="footer-note"><span><span className="live-dot" />{result?.system_status?.message ?? 'Live investigation workspace'}</span><span>{result ? `${result.tool_calls.length} tool calls recorded` : 'No investigation run'}</span><span>Build 0.8.4 · deterministic mode</span></div></div></main></div>
}
function Timeline({ result }: { result: InvestigationResult | null }) { return <div className="timeline">{(result ? result.tool_calls : [{ name: 'Ready for investigation', provenance: 'Select a case and run Investigate', status: 'success' }]).map((item, index) => <div key={`${item.name}-${index}`}><span className={cn('timeline-dot', item.status === 'success' ? 'done' : 'active')} /><div><strong>{item.name}</strong><span>{item.provenance}</span><small>{result ? item.status : 'idle'}</small></div></div>)}</div> }
